### ISSUE TITLE
Fealdend pickle error / probably workqueue directory permission issue

### ISSUE THREAD

**Issue by Paradoxdruid** [23jodys/fealden#14]
Latest Fealden errors out, see output & traceback from webfealden.py below:
###### 

`python webfealden.py
http://0.0.0.0:8080/
127.0.0.1:48363 - - [12/Jun/2013 13:08:05] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:48363 - - [12/Jun/2013 13:08:07] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
127.0.0.1:48370 - - [12/Jun/2013 13:08:18] "HTTP/1.1 POST /" - 303 See Other
Traceback (most recent call last):
  File "bin/fealdend", line 73, in <module>
    main()
  File "bin/fealdend", line 63, in main
    request = workqueue.get()
  File "/media/cargo/fealden/fealden/util.py", line 684, in get
    request = pickle.load(open(fullfile))
  File "/usr/lib/python2.6/pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.6/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.6/pickle.py", line 880, in load_eof
    raise EOFError
EOFError`
######

**Comment by Paradoxdruid** [comment]
Zombie process error.

**Comment by 23jodys** [comment]
Was it a fealdend process that you couldn't kill? Because that is related
to issue #1

**Comment by Paradoxdruid** [comment]
Yeah, fealdend process.

**Comment by 23jodys** [comment]
In that case, #14 will get resolved when I resolve #1, since part of the
issue with getting fealdend to be a proper daemon is getting it to kill its
children.
