### ISSUE TITLE
Gain plots are inaccurate

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#2]
The calculation used to determine gain depends on the difference in free energy between two different structures. Since fealden sensors can have multiple non-optimal structures, this ratio must be determined. The existing code in fealden/weboutput.py is inaccurate.

   # Generate sensor gain graph
    binding_kj = sum([ x["percent_in_solution"] *
                       math.exp(x["energy"])
                       for x in folds
                       if x["type"] == "binding_on" or
                       x["type"] == "binding_unknown"])
    nonbinding_kj = sum([ x["percent_in_solution"] \* x["energy"]
                          for x in folds
                          if x["type"] == "nonbinding_off" or
                          x["type"] == "badnonbind"])
## 

I need more info on exactly what this calculation should look like.

**Comment by Paradoxdruid** [comment]
I have worked out a correct way to calculate the ratio, using some elementary matrix math.  In essence:

Let's say we have 3 folded states.  If we have our dG for each state (state A dG = -8, state B dG = -5, state C dG = -3), then we can use Hess's Law to calculate the dG between states (so A->B has dG = -3, B->C has dG = -2).  From there, we can set up a system of 3 equations with 3 unknowns:

1 (total amount of DNA) = A + B + C

Using our ratio (Keq) to energy equation, dG = -RT ln Keq, we can set up the other to equations as:
(RT is a constant ~ 2.47)

B = A \* e^-3/RT  (this is a number, so we'll call it a constant k1)
C = B \* e^-2/RT (similarly, we can call this k2)

Putting these in linear form gives:
A + B + C = 1
0 + k2B + -C = 0
k1A + -B + 0 = 0

Putting this in Matrix form gives:
(  (1,1,1)
   (0,k2,-1)
   (k1,-1,0)   )    which I'll call M1

and a result Matrix of 
(  (1)
   (0)
   (0)  )   which I'll call M2

To find 
(  (A)
   (B)
   (C)  )  which I'll call M3

We can simply multiply the inverse of our first Matrix by the result Matrix:

Inverse(M1) \* M2   = M3

This solution should be extendable to an arbitrarily large number of states, and works in my sample calculations.  In the example I gave at the beginning, it solves for:
A = .696, B = .209, C = .094
(with k1 = .3 and k2 = .45)

Does that make sense?  If so, I can look into how to do the necessary Matrix math in python, and we can be sure of accurate results.

**Comment by Paradoxdruid** [comment]
This math is actually extremely easy to implement in Python:  http://stackoverflow.com/questions/211160/python-inverse-of-a-matrix

**Comment by 23jodys** [comment]
To clarify, in plotting the gain we plot this function

![equation](http://latex.codecogs.com/gif.latex?%5Cfrac%7B%28k_s%20%5Ccdot%20x%29%7D%7B%28%5Ctext%7Baffinitiy%7D%20%5Ccdot%20%281&plus;k_s%29%29%20&plus;%20k_s%20%5Ccdot%20x%7D) 

where affinity is fixed and x ranges from 10^-9 to 10^-3

Will we be able to extract k_s directly from the above calculation by figuring the ratio of binding_on to nonbinding_off?

**Comment by Paradoxdruid** [comment]
Thanks for the inquiry.  The final Ks is related to the ratio of binding_on and nonbinding_off by:

Ks = (total of binding / total of nonbinding)

So yes, straightforward use of the ratio.

**Comment by 23jodys** [comment]
Fixed and merged back to master.
