### ISSUE TITLE
Configuration file not used

### ISSUE THREAD

**Issue by Paradoxdruid** [23jodys/fealden#20]
This is a repeat of Issue #9 , which was closed.  The latest Fealden build does not respect fealden.ini (when var directory is remapped to /media/cargo/fealden/var, fealdend daemon still tries to use /var ).

**Comment by 23jodys** [comment]
Fixed this, there was a bug where the DaemonContext tried to use a lockfile that was hardcoded. Additionally, fealdend will now try to create the neccesary directories, if they don't already exist.
