### ISSUE TITLE
Update dependencies in documentation

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#8]
Add 
- setproctitle
- python-daemon
- parseargs
- numpy
- matplotlib

**Comment by Paradoxdruid** [comment]
Additional dependency:  
- nose

**Comment by Paradoxdruid** [comment]
Additional dependency:
- ImageMagick

**Comment by Paradoxdruid** [comment]
Additional dependency:
- mfold_util from http://mfold.rna.albany.edu/?q=mfold/download-mfold
