### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by 23jodys** [23jodys/fealden#9]
To store runtime parameters, e.g. workqueue location, solution cache, etc.

**Comment by Paradoxdruid** [comment]
This would be useful; /var/fealden, /var/fealden/solutions, _and_ /var/fealden/workqueue currently must be manually created and require sudo or root to access.

**Comment by 23jodys** [comment]
Commited basic solution for this.

**Comment by Paradoxdruid** [comment]
This issue should be re-opened.  Latest Fealden build does not respect fealden.ini (when var directory is remapped, fealdend daemon still tries to use /var ).
